# Generated by Django 4.0.2 on 2023-06-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
